### ISSUE TITLE
Firebase user datas

### ISSUE THREAD

**Issue by sezeralaca** [Wise10673226/flutter_email_password_login#1]
Hello and thank you for posting this code online. I'm trying to save user datas to my firebase but I failed really bad. I hope you can help me. Thanks in advance

**Comment by Wise10673226** [comment]
Yes bro, using my source code you can be helped and I’ll also recommend the
YouTube video I used for it

**Comment by Wise10673226** [comment]
https://youtu.be/3DO6Th9A7mY

That’s the YouTube video I used


https://chat.whatsapp.com/GXkHtOskZkA77Ok0tsIzWW

That’s also a WhatsApp group where we help others

**Comment by sezeralaca** [comment]
Thank you so much for your help! It really helped me a lot

**Comment by Wise10673226** [comment]
Awesome, thanks!
